### ISSUE TITLE
How do you pick a good song for karaoke?

### ISSUE THREAD

**Issue by PSchwisow** [elazar/amas#4]
- How do you pick a good song to sing for karaoke?
- What song do you think you sing best?
- What is a song that you wish you could sing but it doesn't fit your voice?

**Comment by elazar** [comment]
Really great questions!

Which song I pick actually depends on a number of variables:
- Primarily, the venue and what they have in their catalog, since that limits my choices.
- Who I may be there with. Sometimes I'll do songs I know they'll like, or do duets with them.
- What the crowd is like, what genre or artists they're singing songs from, and what I think they'd respond best to.
- Whether I'm drinking. I'm likely feeling more adventurous than usual in that case. Whether that means I'm not as aware of my vocal limitations as I should be or I'm just more relaxed is also variable.
- Which songs I happen to think of at the time. I try to keep a running list, in Spotify or on YouTube or what have you, but it's limited compared to what I know and am capable of singing.
- My general mood. I may want to sing more upbeat songs or songs from a particular era (e.g. 90's pop, classic rock, etc.) or I may want to sing something more chill or low-tempo.

I'm not sure that I sing any song particularly better than any others. It's difficult to recall specific instances where I had a substantial crowd response, which is the main thing I look for after a song: the better their response, the more fun it is to share the experience with them. I've had people come up and compliment me afterward, give me a high five, buy me a drink (which is awesome), or (what I consider to be one of the highest compliments I can receive) ask me to sing a song with them.

I do remember one instance where I was at a restaurant that had karaoke in Buffalo, New York with a couple of friends. There was an elderly African American gentlemen who happened to be there and had seen Hootie and the Blowfish perform live fairly recently. ["Let Her Cry"](https://www.youtube.com/watch?v=1aVHLL5egRY) is a song I've been singing longer than most and I happened to decide to perform it then. He called me over afterward and said that, next to Darius Rucker himself, I'd given the best performance of the song he'd ever heard. I think that's one of the better compliments I've ever received.

I'm not sure I can name a single song I'd like to do that doesn't fit my voice. Most of the songs to which that applies are above my range. The artists I like -- Train, Jason Mraz, Rascal Flatts, and so forth -- have fairly high upper bounds to their range that I can only come remotely close to on fairly good nights. I'd also like to be able to do more crossover songs; I've done an okay job of "Make You Feel My Love" by Adele before.
