### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [elazar/amas#6]

**Comment by elazar** [comment]
Indeed.
- I participated as a mentor in the [PHP Women](http://phpwomen.org) Big Sis / Little Sis mentorship program between 2008 and 2012. I've continued to participate since that program was spun off into the [PHP Mentoring](http://phpmentoring.org) program in 2012.
- I recently participated for one session in [Prime Digital Academy](https://www.facebook.com/primedigitalacademy?fref=nf)'s Developmentor program.
- I've been speaking at conferences on and off since 2008, which I think can be classified as a means of mentorship.
